### ISSUE TITLE
Int32 casts on expand are not handled correctly

### ISSUE THREAD

**Issue by kaovd** [magodo/terrassist#6]
When an SDK has a type of int32 rather than int64, assumption is made downstream is set as int32 - generally within terraform Schema the only availaible type on definition is TypeInt which is int64 by default - this needs to be cast to int32 on expand as it attempts to interface as a standard int causing provider crash

This isnt an issue on flatten as this is handled correctly as there is no issue going Int32 > 64 

What is rendered as 
```
utils.Int32(b["duration_in_days"].(int32)),
```
Should be rendered as 
```
utils.Int32(int32(b["duration_in_days"].(int))),
```

**Comment by magodo** [comment]
@kaovd Thank you for pointing this out!
